import type { Metadata } from "next";
import { Comic_Neue } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/components/ConvexClientProvider";
import ClientProvider from "@/components/ClientProvider";
import "./globals.css";
import "@stream-io/video-react-sdk/dist/css/styles.css";

const comicNeue = Comic_Neue({
  variable: "--font-comic-neue",
  weight: ["300", "400", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${comicNeue.variable} antialiased`}
          suppressHydrationWarning
        >
          <ClientProvider>
            <ConvexClientProvider>{children}</ConvexClientProvider>
          </ClientProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
